# Generated by Django 5.2.5 on 2025-08-14 15:53

from django.db import migrations

def create_initial_data(apps, schema_editor):
    Gender = apps.get_model('accounts', 'Gender')
    Role = apps.get_model('accounts', 'Role')
    
    Gender.objects.bulk_create([
        Gender(name='Муж.'),
        Gender(name='Жен.'),
    ])
    
    Role.objects.bulk_create([
        Role(name='Админитсратор'),
        Role(name='Пользователь'),
        Role(name='Курьер'),
    ])

class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_user_is_active_remove_user_is_staff_and_more'),
    ]

    operations = [
        migrations.RunPython(create_initial_data),
    ]
