# Generated by Django 5.2.4 on 2025-10-02 21:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickup', models.BooleanField(default=False, verbose_name='Самовывоз')),
                ('street', models.CharField(blank=True, max_length=255, null=True)),
                ('house', models.CharField(blank=True, max_length=10, null=True)),
                ('entrance', models.CharField(blank=True, max_length=10, null=True)),
                ('flat', models.CharField(blank=True, max_length=10, null=True)),
                ('intercom', models.CharField(blank=True, max_length=20, null=True)),
                ('phone', models.CharField(max_length=20)),
                ('persons', models.PositiveIntegerField(default=1)),
                ('comment', models.TextField(blank=True, null=True)),
                ('payment', models.CharField(choices=[('cash', 'Наличные'), ('card', 'Картой при получении')], default='cash', max_length=10)),
                ('status', models.CharField(choices=[('processing', 'В обработке'), ('preparing', 'Готовится'), ('delivering', 'Доставляется'), ('completed', 'Завершён')], default='processing', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('courier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliveries', to=settings.AUTH_USER_MODEL, verbose_name='Курьер')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='Заказчик')),
            ],
        ),
    ]
