# Generated by Django 5.2.4 on 2025-10-05 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='category',
            field=models.CharField(default='other', max_length=50, verbose_name='Категория'),
        ),
    ]
